

base: &base
  image: python:2.7-wheezy


dev: &dev_base
  <<: *base
  ports:
    - "4040:4040"
  environment:
    DATABASE_NAME: app_development
    RACK_ENV: development
    RAILS_ENV: development
